<div class="l-menu">
    <a class="left-a <?php if($menu=='1'){echo 'active';}?>" href="<?php echo FATHER_BASE;?>"><span class="xflex"><span class="lnr lnr-home"></span> Anasayfa</span> <?php if($menu=='1'){echo '<i class="fa fa-chevron-right"></i>';}?></a>
    <!--<a class="left-a <?php if($menu=='1_1'){echo 'active';}?>" href="<?php echo CATEGORY_LIST;?>"><span class="xflex"><span class="lnr lnr-list"></span> Kategoriler </span> <?php if($menu=='1_1'){echo '<i class="fa fa-chevron-right"></i>';}?></a>-->
    <a class="left-a <?php if($menu=='2'){echo 'active';}?>" href="<?php echo PRODUCT_LIST;?>"><span class="xflex"><span class="lnr lnr-star"></span> Ürünler </span> <?php if($menu=='2'){echo '<i class="fa fa-chevron-right"></i>';}?></a>
    <a class="left-a <?php if($menu=='2_1'){echo 'active';}?>" href="<?php echo UPLOAD_EXCEL;?>"><span class="xflex"><span class="lnr lnr-file-add"></span> Excel Yükleme </span> <?php if($menu=='2_1'){echo '<i class="fa fa-chevron-right"></i>';}?></a>
    <!--<a class="left-a <?php if($menu=='21'){echo 'active';}?>" href="<?php echo ADD_RESTAURANT;?>"><span class="xflex"><i class="fa fa-user-plus"></i> New Restaurant </span> <?php if($menu=='21'){echo '<i class="fa fa-chevron-right"></i>';}?></a>-->
    <a class="left-a <?php if($menu=='4'){echo 'active';}?>" href="<?php echo PAGE_LIST;?>"><span class="xflex"><span class="lnr lnr-book"></span> Sayfalar</span> <?php if($menu=='4'){echo '<i class="fa fa-chevron-right"></i>';}?></a>
    <a class="left-a <?php if($menu=='5'){echo 'active';}?>" href="<?php echo SOCIAL_MEDIA_LIST;?>"><span class="xflex"><span class="lnr lnr-link"></span> Sosyal Medya</span> <?php if($menu=='5'){echo '<i class="fa fa-chevron-right"></i>';}?></a>
    <a class="left-a <?php if($menu=='6'){echo 'active';}?>" href="<?php echo BANNER_LIST;?>"><span class="xflex"><span class="lnr lnr-picture"></span> Slaytlar</span> <?php if($menu=='6'){echo '<i class="fa fa-chevron-right"></i>';}?></a>
</div>